name: RimWorld Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  rimworld-deploy:
      uses: MemeGoddess/RimWorld-Deployment-Pipeline/.github/workflows/deploy.yml@beta
      secrets: inherit
      with:
          # This is a private workshop ID that I use as staging
          # I highly recommend you have one as well
          # Only update after you've deployed to staging and confirmed it works
          workshopId: '3526439840' 
          
          # ex: 'Source/RimMod.csproj, ModCompat/X/X.csproj'
          # optional, will skip building if not provided
          # ExcludedProjectFiles: 'Source/RimMod.csproj' 